import { PieceType, DirType } from "../types/pieceTypes.ts";

export const BOARD_SIZE = {
  padding: 30 * (375 / 600),
  width: 540 * (375 / 600),
  height: 560 * (375 / 600),
  rows: 9,
  cols: 9,
};
export const PIECE_SIZE = {
  width: 60 * (375 / 600),
  height: 62 * (375 / 600),
};

export const PIECE_DIRECTIONS = [
  [0, -1],
  [1, -1],
  [1, 0],
  [1, 1],
  [0, 1],
  [-1, 1],
  [-1, 0],
  [-1, -1],
  [1, -2],
  [-1, -2],
];

export const MOVABLE_RANGES: { [key in PieceType]: number[] } = {
  [PieceType.None]: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [PieceType.King1]: [1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
  [PieceType.King2]: [1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
  [PieceType.Rook]: [9, 0, 9, 0, 9, 0, 9, 0, 0, 0],
  [PieceType.Bishop]: [0, 9, 0, 9, 0, 9, 0, 9, 0, 0],
  [PieceType.Gold]: [1, 1, 1, 0, 1, 0, 1, 1, 0, 0],
  [PieceType.Silver]: [1, 1, 0, 1, 0, 1, 0, 1, 0, 0],
  [PieceType.Knight]: [0, 0, 0, 0, 0, 0, 0, 0, 2, 2],
  [PieceType.Lance]: [9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [PieceType.Pawn]: [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [PieceType.PromotedRook]: [9, 1, 9, 1, 9, 1, 9, 1, 0, 0],
  [PieceType.PromotedBishop]: [1, 9, 1, 9, 1, 9, 1, 9, 0, 0],
  [PieceType.PromotedSilver]: [1, 1, 1, 0, 1, 0, 1, 1, 0, 0],
  [PieceType.PromotedKnight]: [1, 1, 1, 0, 1, 0, 1, 1, 0, 0],
  [PieceType.PromotedLance]: [1, 1, 1, 0, 1, 0, 1, 1, 0, 0],
  [PieceType.PromotedPawn]: [1, 1, 1, 0, 1, 0, 1, 1, 0, 0],
};

export const PIECES = [
  {
    type: PieceType.King1,
    promoted: PieceType.None,
    orgType: PieceType.King1,
    direction: DirType.Up,
    image: "u_king1.png",
    movableRange: MOVABLE_RANGES[PieceType.King1],
  },
  {
    type: PieceType.King2,
    promoted: PieceType.None,
    orgType: PieceType.King2,
    direction: DirType.Up,
    image: "u_king2.png",
    movableRange: MOVABLE_RANGES[PieceType.King2],
  },
  {
    type: PieceType.Rook,
    promoted: PieceType.PromotedRook,
    orgType: PieceType.Rook,
    direction: DirType.Up,
    image: "u_rook.png",
    movableRange: MOVABLE_RANGES[PieceType.Rook],
  },
  {
    type: PieceType.Bishop,
    promoted: PieceType.PromotedBishop,
    orgType: PieceType.Bishop,
    direction: DirType.Up,
    image: "u_bishop.png",
    movableRange: MOVABLE_RANGES[PieceType.Bishop],
  },
  {
    type: PieceType.Gold,
    promoted: PieceType.None,
    orgType: PieceType.Gold,
    direction: DirType.Up,
    image: "u_gold.png",
    movableRange: MOVABLE_RANGES[PieceType.Gold],
  },
  {
    type: PieceType.Silver,
    promoted: PieceType.PromotedSilver,
    orgType: PieceType.Silver,
    direction: DirType.Up,
    image: "u_silver.png",
    movableRange: MOVABLE_RANGES[PieceType.Silver],
  },
  {
    type: PieceType.Knight,
    promoted: PieceType.PromotedKnight,
    orgType: PieceType.Knight,
    direction: DirType.Up,
    image: "u_knight.png",
    movableRange: MOVABLE_RANGES[PieceType.Knight],
  },
  {
    type: PieceType.Lance,
    promoted: PieceType.PromotedLance,
    orgType: PieceType.Lance,
    direction: DirType.Up,
    image: "u_lance.png",
    movableRange: MOVABLE_RANGES[PieceType.King1],
  },
  {
    type: PieceType.Pawn,
    promoted: PieceType.PromotedPawn,
    orgType: PieceType.Pawn,
    direction: DirType.Up,
    image: "u_pawn.png",
    movableRange: MOVABLE_RANGES[PieceType.Lance],
  },
  {
    type: PieceType.PromotedRook,
    promoted: PieceType.None,
    orgType: PieceType.Rook,
    direction: DirType.Up,
    image: "u_p_rook.png",
    movableRange: MOVABLE_RANGES[PieceType.PromotedRook],
  },
  {
    type: PieceType.PromotedBishop,
    promoted: PieceType.None,
    orgType: PieceType.Bishop,
    direction: DirType.Up,
    image: "u_p_bishop.png",
    movableRange: MOVABLE_RANGES[PieceType.PromotedBishop],
  },
  {
    type: PieceType.PromotedSilver,
    promoted: PieceType.None,
    orgType: PieceType.Silver,
    direction: DirType.Up,
    image: "u_p_silver.png",
    movableRange: MOVABLE_RANGES[PieceType.PromotedSilver],
  },
  {
    type: PieceType.PromotedKnight,
    promoted: PieceType.None,
    orgType: PieceType.Knight,
    direction: DirType.Up,
    image: "u_p_knight.png",
    movableRange: MOVABLE_RANGES[PieceType.PromotedKnight],
  },
  {
    type: PieceType.PromotedLance,
    promoted: PieceType.None,
    orgType: PieceType.Lance,
    direction: DirType.Up,
    image: "u_p_lance.png",
    movableRange: MOVABLE_RANGES[PieceType.PromotedLance],
  },
  {
    type: PieceType.PromotedPawn,
    promoted: PieceType.None,
    orgType: PieceType.Pawn,
    direction: DirType.Up,
    image: "u_p_pawn.png",
    movableRange: MOVABLE_RANGES[PieceType.PromotedPawn],
  },
  {
    type: PieceType.King1,
    promoted: PieceType.None,
    orgType: PieceType.King1,
    direction: DirType.Down,
    image: "d_king1.png",
    movableRange: MOVABLE_RANGES[PieceType.King1],
  },
  {
    type: PieceType.King2,
    promoted: PieceType.None,
    orgType: PieceType.King2,
    direction: DirType.Down,
    image: "d_king2.png",
    movableRange: MOVABLE_RANGES[PieceType.King2],
  },
  {
    type: PieceType.Rook,
    promoted: PieceType.PromotedRook,
    orgType: PieceType.Rook,
    direction: DirType.Down,
    image: "d_rook.png",
    movableRange: MOVABLE_RANGES[PieceType.Rook],
  },
  {
    type: PieceType.Bishop,
    promoted: PieceType.PromotedBishop,
    orgType: PieceType.Bishop,
    direction: DirType.Down,
    image: "d_bishop.png",
    movableRange: MOVABLE_RANGES[PieceType.Bishop],
  },
  {
    type: PieceType.Gold,
    promoted: PieceType.None,
    orgType: PieceType.Gold,
    direction: DirType.Down,
    image: "d_gold.png",
    movableRange: MOVABLE_RANGES[PieceType.Gold],
  },
  {
    type: PieceType.Silver,
    promoted: PieceType.PromotedSilver,
    orgType: PieceType.Silver,
    direction: DirType.Down,
    image: "d_silver.png",
    movableRange: MOVABLE_RANGES[PieceType.Silver],
  },
  {
    type: PieceType.Knight,
    promoted: PieceType.PromotedKnight,
    orgType: PieceType.Knight,
    direction: DirType.Down,
    image: "d_knight.png",
    movableRange: MOVABLE_RANGES[PieceType.Knight],
  },
  {
    type: PieceType.Lance,
    promoted: PieceType.PromotedLance,
    orgType: PieceType.Lance,
    direction: DirType.Down,
    image: "d_lance.png",
    movableRange: MOVABLE_RANGES[PieceType.Lance],
  },
  {
    type: PieceType.Pawn,
    promoted: PieceType.PromotedPawn,
    orgType: PieceType.Pawn,
    direction: DirType.Down,
    image: "d_pawn.png",
    movableRange: MOVABLE_RANGES[PieceType.Pawn],
  },
  {
    type: PieceType.PromotedRook,
    promoted: PieceType.None,
    orgType: PieceType.Rook,
    direction: DirType.Down,
    image: "d_p_rook.png",
    movableRange: MOVABLE_RANGES[PieceType.PromotedRook],
  },
  {
    type: PieceType.PromotedBishop,
    promoted: PieceType.None,
    orgType: PieceType.Bishop,
    direction: DirType.Down,
    image: "d_p_bishop.png",
    movableRange: MOVABLE_RANGES[PieceType.PromotedBishop],
  },
  {
    type: PieceType.PromotedSilver,
    promoted: PieceType.None,
    orgType: PieceType.Silver,
    direction: DirType.Down,
    image: "d_p_silver.png",
    movableRange: MOVABLE_RANGES[PieceType.PromotedSilver],
  },
  {
    type: PieceType.PromotedKnight,
    promoted: PieceType.None,
    orgType: PieceType.Knight,
    direction: DirType.Down,
    image: "d_p_knight.png",
    movableRange: MOVABLE_RANGES[PieceType.PromotedKnight],
  },
  {
    type: PieceType.PromotedLance,
    promoted: PieceType.None,
    orgType: PieceType.Lance,
    direction: DirType.Down,
    image: "d_p_lance.png",
    movableRange: MOVABLE_RANGES[PieceType.PromotedLance],
  },
  {
    type: PieceType.PromotedPawn,
    promoted: PieceType.None,
    orgType: PieceType.Pawn,
    direction: DirType.Down,
    image: "d_p_pawn.png",
    movableRange: MOVABLE_RANGES[PieceType.PromotedPawn],
  },
];
